security:
  basic:
    enabled: false
  oauth2:
    client:
      access-token-uri: http://localhost:8081/auth/oauth/token
      user-authorization-uri: http://localhost:8081/auth/oauth/authorize
      clientId: SampleClientId
      clientSecret: secret
    resource:
      user-info-uri: http://localhost:8081/auth/user/me
      token-info-uri: http://localhost:8081/auth/oauth/check_token

spring:
  thymeleaf:
    cache: false